### ISSUE TITLE
小白来问，如何使用

### ISSUE THREAD

**Issue by benladen** [zzhoo8/ximalaya-downloader#6]
PY3.6.8，CMD运行出现如下错误，如何使用？
Traceback (most recent call last):
  File "ximalaya.py", line 4, in <module>
    from downloader.models.ximalaya import Album
ModuleNotFoundError: No module named 'downloader'

**Comment by zzhoo8** [comment]
> PY3.6.8，CMD运行出现如下错误，如何使用？
> Traceback (most recent call last):
> File "ximalaya.py", line 4, in 
> from downloader.models.ximalaya import Album
> ModuleNotFoundError: No module named 'downloader'

重新调整了目录结构，命令行直接运行不会报错了。**请更新master分支**

PS：建议任何python项目运行之前需要
1. 创建虚拟环境
2. 安装依赖（本工程在app/requirements.txt）
3. 运行`python -m run.py`，Have fun!

**Comment by benladen** [comment]
感谢回复。
我尽可能去学习了，然后还是出现错误了，小白伤不起。。

(venv) F:\Download\ximalaya\ximalaya-downloader-master>python -m run.py
F:\Download\ximalaya\ximalaya-downloader-master\venv\Scripts\python.exe: Error while finding module specification for 'run.py' (AttributeError: module 'run' has no attribute '__path__')

**Comment by zzhoo8** [comment]
> 感谢回复。
> 我尽可能去学习了，然后还是出现错误了，小白伤不起。。
> 
> (venv) F:\Download\ximalaya\ximalaya-downloader-master>python -m run.py
> F:\Download\ximalaya\ximalaya-downloader-master\venv\Scripts\python.exe: Error while finding module specification for 'run.py' (AttributeError: module 'run' has no attribute '**path**')

没关系，我又更新了`master`分支

最后一步使用命令`python run.py`即可（本机试验通过）

**Comment by benladen** [comment]
的确OK了，只是有个小bug，创建目录了，但是下载的文件还在run的目录中

**Comment by zzhoo8** [comment]
> 的确OK了，只是有个小bug，创建目录了，但是下载的文件还在run的目录中

更新之后已经修复了这个问题。
